-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agent_decisions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  run_id uuid,
  decision_type text NOT NULL,
  decision_data jsonb NOT NULL,
  signature text NOT NULL,
  public_key text NOT NULL,
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'failed'::text])),
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_decisions_pkey PRIMARY KEY (id),
  CONSTRAINT agent_decisions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agent_decisions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_instances(id),
  CONSTRAINT agent_decisions_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.agent_runs(id)
);
CREATE TABLE public.agent_executions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_id text NOT NULL,
  execution_type text NOT NULL CHECK (execution_type = ANY (ARRAY['task'::text, 'query'::text, 'learning'::text, 'inference'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  input_data jsonb NOT NULL,
  output_data jsonb,
  error_message text,
  metrics jsonb DEFAULT '{}'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  duration_ms integer,
  tokens_used integer DEFAULT 0,
  cost_usd numeric DEFAULT 0,
  parent_execution_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT agent_executions_pkey PRIMARY KEY (id),
  CONSTRAINT agent_executions_parent_fk FOREIGN KEY (parent_execution_id) REFERENCES public.agent_executions(id)
);
CREATE TABLE public.agent_failures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  run_id uuid,
  failure_type text NOT NULL,
  error_message text NOT NULL,
  context jsonb DEFAULT '{}'::jsonb,
  reflection text,
  resolution text,
  learned_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_failures_pkey PRIMARY KEY (id),
  CONSTRAINT agent_failures_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agent_failures_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_instances(id),
  CONSTRAINT agent_failures_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.agent_runs(id)
);
CREATE TABLE public.agent_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  swarm_id uuid,
  agent_id text NOT NULL,
  agent_type text NOT NULL CHECK (agent_type = ANY (ARRAY['researcher'::text, 'coder'::text, 'analyst'::text, 'optimizer'::text, 'coordinator'::text])),
  status text NOT NULL DEFAULT 'idle'::text CHECK (status = ANY (ARRAY['idle'::text, 'busy'::text, 'error'::text, 'terminated'::text])),
  capabilities jsonb DEFAULT '[]'::jsonb,
  performance_metrics jsonb DEFAULT '{}'::jsonb,
  last_heartbeat_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_instances_pkey PRIMARY KEY (id),
  CONSTRAINT agent_instances_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agent_instances_swarm_id_fkey FOREIGN KEY (swarm_id) REFERENCES public.agent_swarms(id)
);
CREATE TABLE public.agent_keypairs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_id uuid NOT NULL UNIQUE,
  public_key text NOT NULL,
  encrypted_private_key text NOT NULL,
  encryption_key_id text NOT NULL,
  nonce text NOT NULL,
  algorithm text NOT NULL DEFAULT 'ed25519'::text CHECK (algorithm = ANY (ARRAY['ed25519'::text, 'rsa'::text, 'ecdsa'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  rotated_at timestamp with time zone,
  expires_at timestamp with time zone,
  CONSTRAINT agent_keypairs_pkey PRIMARY KEY (id),
  CONSTRAINT agent_keypairs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agent_keypairs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_instances(id)
);
CREATE TABLE public.agent_memories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  memory_type text NOT NULL CHECK (memory_type = ANY (ARRAY['interaction'::text, 'skill'::text, 'reflection'::text, 'episodic'::text, 'semantic'::text])),
  content text NOT NULL CHECK (char_length(content) >= 1),
  embedding USER-DEFINED,
  metadata jsonb DEFAULT '{}'::jsonb,
  causal_links ARRAY,
  importance_score numeric NOT NULL DEFAULT 0.5 CHECK (importance_score >= 0::numeric AND importance_score <= 1::numeric),
  access_count integer NOT NULL DEFAULT 0,
  last_accessed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT agent_memories_pkey PRIMARY KEY (id),
  CONSTRAINT agent_memories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agent_memories_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_instances(id)
);
CREATE TABLE public.agent_memory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_id text NOT NULL,
  memory_type text NOT NULL CHECK (memory_type = ANY (ARRAY['short_term'::text, 'long_term'::text, 'episodic'::text, 'semantic'::text])),
  content text NOT NULL,
  embedding USER-DEFINED,
  metadata jsonb DEFAULT '{}'::jsonb,
  importance_score double precision DEFAULT 0.5 CHECK (importance_score >= 0::double precision AND importance_score <= 1::double precision),
  access_count integer DEFAULT 0,
  last_accessed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT agent_memory_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_instance_id uuid NOT NULL,
  task_id uuid,
  sandbox_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  input_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  output_data jsonb,
  error_message text,
  metrics jsonb DEFAULT '{}'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  duration_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_runs_pkey PRIMARY KEY (id),
  CONSTRAINT agent_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agent_runs_agent_instance_id_fkey FOREIGN KEY (agent_instance_id) REFERENCES public.agent_instances(id),
  CONSTRAINT agent_runs_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);
CREATE TABLE public.agent_skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  skill_name text NOT NULL,
  skill_type text NOT NULL,
  description text,
  implementation jsonb NOT NULL,
  performance_score numeric DEFAULT 0.5 CHECK (performance_score >= 0::numeric AND performance_score <= 1::numeric),
  usage_count integer NOT NULL DEFAULT 0,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_skills_pkey PRIMARY KEY (id),
  CONSTRAINT agent_skills_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agent_skills_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_instances(id)
);
CREATE TABLE public.agent_swarms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  project_id uuid,
  name text NOT NULL CHECK (char_length(name) >= 1 AND char_length(name) <= 200),
  topology text NOT NULL DEFAULT 'mesh'::text CHECK (topology = ANY (ARRAY['mesh'::text, 'hierarchical'::text, 'ring'::text, 'star'::text])),
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'idle'::text CHECK (status = ANY (ARRAY['idle'::text, 'active'::text, 'paused'::text, 'terminated'::text])),
  agent_count integer NOT NULL DEFAULT 0 CHECK (agent_count >= 0),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_swarms_pkey PRIMARY KEY (id),
  CONSTRAINT agent_swarms_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT agent_swarms_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT agent_swarms_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.artifacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_run_id uuid,
  task_id uuid,
  artifact_type text NOT NULL CHECK (artifact_type = ANY (ARRAY['file'::text, 'image'::text, 'code'::text, 'log'::text, 'report'::text, 'model'::text])),
  name text NOT NULL,
  storage_path text NOT NULL,
  size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
  mime_type text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT artifacts_pkey PRIMARY KEY (id),
  CONSTRAINT artifacts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT artifacts_agent_run_id_fkey FOREIGN KEY (agent_run_id) REFERENCES public.agent_runs(id),
  CONSTRAINT artifacts_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT artifacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id uuid,
  old_data jsonb,
  new_data jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.billing_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['subscription_created'::text, 'subscription_updated'::text, 'subscription_cancelled'::text, 'payment_succeeded'::text, 'payment_failed'::text, 'invoice_created'::text, 'refund_issued'::text])),
  amount_usd numeric,
  currency text DEFAULT 'USD'::text,
  stripe_event_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_events_pkey PRIMARY KEY (id),
  CONSTRAINT billing_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.consensus_lineage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  project text NOT NULL,
  section_tag text,
  task_id uuid,
  run_id uuid,
  contributing_experts jsonb NOT NULL,
  winning_version text,
  confidence double precision,
  final_decision jsonb NOT NULL,
  disagreement_score double precision,
  reasoning_chains jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consensus_lineage_pkey PRIMARY KEY (id),
  CONSTRAINT consensus_lineage_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.expert_signatures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  project text NOT NULL,
  expert_id text NOT NULL,
  version text NOT NULL,
  prompt text NOT NULL,
  signature jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  performance_metrics jsonb DEFAULT '{}'::jsonb,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expert_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT expert_signatures_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.iris_api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id text NOT NULL,
  project_name text NOT NULL,
  api_key_hash text NOT NULL UNIQUE,
  api_key_prefix text NOT NULL,
  label text NOT NULL,
  last_used_at timestamp with time zone,
  usage_count bigint DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT iris_api_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.iris_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid,
  project text NOT NULL,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['project_evaluation'::text, 'cross_project'::text, 'auto_retrain'::text, 'rotation'::text, 'pattern_transfer'::text])),
  health_score integer NOT NULL CHECK (health_score >= 0 AND health_score <= 100),
  overall_health text NOT NULL CHECK (overall_health = ANY (ARRAY['healthy'::text, 'degraded'::text, 'critical'::text])),
  drift_alerts_count integer DEFAULT 0,
  recommended_actions_count integer DEFAULT 0,
  report_data jsonb NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT iris_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.iris_telemetry (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id text NOT NULL,
  expert_id text NOT NULL,
  confidence numeric,
  latency_ms integer,
  outcome text,
  event_type text DEFAULT 'telemetry'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT iris_telemetry_pkey PRIMARY KEY (id)
);
CREATE TABLE public.memberships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text, 'viewer'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  invited_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT memberships_pkey PRIMARY KEY (id),
  CONSTRAINT memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT memberships_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.model_run_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  project text NOT NULL,
  expert_id text NOT NULL,
  version text,
  run_id uuid,
  input_hash text,
  confidence double precision,
  latency_ms integer,
  tokens_in integer,
  tokens_out integer,
  cost_usd numeric,
  outcome text,
  reflexion_used boolean DEFAULT false,
  reflexion_ids ARRAY,
  consensus_participation boolean DEFAULT false,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT model_run_log_pkey PRIMARY KEY (id),
  CONSTRAINT model_run_log_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL CHECK (char_length(name) >= 1 AND char_length(name) <= 200),
  description text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'archived'::text, 'deleted'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.rate_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  resource_type text NOT NULL,
  limit_value integer NOT NULL,
  window_seconds integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reflexion_bank (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  project text NOT NULL,
  expert_id text,
  reflexion_type text NOT NULL,
  embedding USER-DEFINED,
  context jsonb NOT NULL,
  outcome jsonb NOT NULL,
  success boolean NOT NULL,
  confidence double precision,
  impact_score double precision DEFAULT 0.5 CHECK (impact_score >= 0::double precision AND impact_score <= 1::double precision),
  reuse_count integer DEFAULT 0,
  last_reused_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reflexion_bank_pkey PRIMARY KEY (id),
  CONSTRAINT reflexion_bank_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.research_citations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  research_job_id uuid NOT NULL,
  title text NOT NULL,
  authors ARRAY,
  publication_date date,
  source text NOT NULL,
  url text,
  doi text,
  citation_text text,
  relevance_score numeric CHECK (relevance_score >= 0::numeric AND relevance_score <= 1::numeric),
  verified boolean NOT NULL DEFAULT false,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT research_citations_pkey PRIMARY KEY (id),
  CONSTRAINT research_citations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT research_citations_research_job_id_fkey FOREIGN KEY (research_job_id) REFERENCES public.research_jobs(id)
);
CREATE TABLE public.research_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  agent_run_id uuid,
  query text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'researching'::text, 'completed'::text, 'failed'::text])),
  search_strategy jsonb DEFAULT '{}'::jsonb,
  results jsonb,
  citation_count integer DEFAULT 0,
  quality_score numeric CHECK (quality_score >= 0::numeric AND quality_score <= 1::numeric),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT research_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT research_jobs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT research_jobs_agent_run_id_fkey FOREIGN KEY (agent_run_id) REFERENCES public.agent_runs(id)
);
CREATE TABLE public.sandboxes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  e2b_sandbox_id text NOT NULL UNIQUE,
  template text NOT NULL,
  status text NOT NULL DEFAULT 'creating'::text CHECK (status = ANY (ARRAY['creating'::text, 'running'::text, 'stopped'::text, 'terminated'::text, 'failed'::text])),
  env_vars jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  cpu_usage_percent numeric,
  memory_usage_mb integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  terminated_at timestamp with time zone,
  last_heartbeat_at timestamp with time zone,
  CONSTRAINT sandboxes_pkey PRIMARY KEY (id),
  CONSTRAINT sandboxes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.security_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['threat'::text, 'anomaly'::text, 'violation'::text, 'rate_limit'::text, 'unauthorized_access'::text])),
  severity text NOT NULL DEFAULT 'low'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  threat_score numeric DEFAULT 0.0 CHECK (threat_score >= 0::numeric AND threat_score <= 1::numeric),
  source_ip inet,
  user_id uuid,
  agent_id uuid,
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  blocked boolean NOT NULL DEFAULT false,
  resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_events_pkey PRIMARY KEY (id),
  CONSTRAINT security_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT security_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT security_events_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent_instances(id)
);
CREATE TABLE public.signature_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  project text NOT NULL,
  expert_id text NOT NULL,
  from_version text,
  to_version text,
  changelog text,
  diff jsonb,
  improvement_metrics jsonb,
  rollback_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT signature_versions_pkey PRIMARY KEY (id),
  CONSTRAINT signature_versions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  project_id uuid,
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'planning'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  input_data jsonb DEFAULT '{}'::jsonb,
  output_data jsonb,
  error_message text,
  assigned_to uuid,
  created_by uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (char_length(name) >= 2 AND char_length(name) <= 100),
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]+$'::text),
  plan text NOT NULL DEFAULT 'free'::text CHECK (plan = ANY (ARRAY['free'::text, 'pro'::text, 'enterprise'::text])),
  limits jsonb NOT NULL DEFAULT '{"maxAgents": 10, "rateLimit": {"tokensPerDay": 100000, "requestsPerMinute": 100}, "maxStorageGB": 1, "maxSandboxMinutes": 60, "maxConcurrentTasks": 5, "maxMemoriesPerAgent": 1000}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.usage_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  resource_type text NOT NULL CHECK (resource_type = ANY (ARRAY['agent_run'::text, 'storage'::text, 'sandbox'::text, 'token'::text, 'api_call'::text])),
  resource_id uuid,
  quantity numeric NOT NULL CHECK (quantity >= 0::numeric),
  unit text NOT NULL,
  cost_usd numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT usage_records_pkey PRIMARY KEY (id),
  CONSTRAINT usage_records_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  email text NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  full_name text,
  avatar_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workflow_executions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  workflow_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  input_data jsonb NOT NULL,
  output_data jsonb,
  current_step text,
  steps_completed integer DEFAULT 0,
  total_steps integer NOT NULL,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  duration_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_executions_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_executions_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.workflows(id)
);
CREATE TABLE public.workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  workflow_type text NOT NULL CHECK (workflow_type = ANY (ARRAY['sequential'::text, 'parallel'::text, 'dag'::text, 'event_driven'::text])),
  definition jsonb NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'archived'::text])),
  version integer DEFAULT 1 CHECK (version > 0),
  execution_count integer DEFAULT 0,
  success_count integer DEFAULT 0,
  failure_count integer DEFAULT 0,
  avg_duration_ms integer,
  last_executed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflows_pkey PRIMARY KEY (id),
  CONSTRAINT workflows_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);